import { useState, useReducer } from "react";
import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  useReactTable,
  getExpandedRowModel,
  getPaginationRowModel,
  getFilteredRowModel,
} from "@tanstack/react-table";
import type { ColumnResizeMode } from "@tanstack/react-table";

import "./App.css";

type Animal = {
  name: string;
  species: string;
  habitat: string;
  age: number;
  status: string;
  progress: number;
  subRows?: Animal[];
};

const data: Animal[] = [
  {
    name: "Leo",
    species: "Lion",
    habitat: "Savannah",
    age: 8,
    status: "Endangered",
    progress: 75,
    subRows: [
      {
        name: "Cub 1",
        species: "Lion",
        habitat: "Savannah",
        age: 1,
        status: "Stable",
        progress: 30,
      },
    ],
  },
  {
    name: "Tuki",
    species: "Elephant",
    habitat: "Rainforest",
    age: 25,
    status: "Vulnerable",
    progress: 60,
  },
  {
    name: "Nori",
    species: "Penguin",
    habitat: "Antarctica",
    age: 4,
    status: "Least Concern",
    progress: 40,
  },
];

type KPIs = {
  targetValue: number;
  inprocessValue: number;
  confirmValue: number;
  validatedValue: number;
  totalValue: number;
  totalVsTargetValue: number;
  totalVsTargetValuePerc: number;
  mixTargetValue: number;
  mixActualValue: number;
  targetQuantity: number;
  inprocessQuantity: number;
  confirmQuantity: number;
  validatedQuantity: number;
  totalQuantity?: number;
  totalVsTargetQuantity: number;
  totalVsTargetQuantityPerc: number;
  mixTargetQuantity: number;
  mixActualQuantity: number;
  nbAcsBuy: number;
  acs: number;
};

type Category = {
  id: string;
  name: string;
  totalProducts: number;
  kpis: KPIs;
  children?: Category[];
};

const columnHelper = createColumnHelper<Category>();

const testData: Category[] = [
  {
    id: "C7748",
    name: "ACCESSORIES",
    totalProducts: 64,
    kpis: {
      targetValue: 0,
      inprocessValue: 680,
      confirmValue: 0,
      validatedValue: 0,
      totalValue: 680,
      totalVsTargetValue: 680,
      totalVsTargetValuePerc: 0,
      mixTargetValue: 0,
      mixActualValue: 9.47,
      targetQuantity: 0,
      inprocessQuantity: 4,
      confirmQuantity: 0,
      validatedQuantity: 0,
      totalQuantity: 4,
      totalVsTargetQuantity: 4,
      totalVsTargetQuantityPerc: 0,
      mixTargetQuantity: 0,
      mixActualQuantity: 0.01,
      nbAcsBuy: 1,
      acs: 64,
    },
    children: [
      {
        id: "C202838",
        name: "BRACELET/CUFF",
        totalProducts: 8,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 8,
        },
        children: [],
      },
      {
        id: "C202837",
        name: "EARRINGS",
        totalProducts: 11,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 11,
        },
        children: [],
      },
      {
        id: "C202836",
        name: "NECKLACE/HANGING",
        totalProducts: 10,
        kpis: {
          targetValue: 0,
          inprocessValue: 680,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 680,
          totalVsTargetValue: 680,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 100,
          targetQuantity: 0,
          inprocessQuantity: 4,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 4,
          totalVsTargetQuantity: 4,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 100,
          nbAcsBuy: 1,
          acs: 10,
        },
        children: [],
      },
      {
        id: "C202831",
        name: "OTHER RTW ACC",
        totalProducts: 4,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 4,
        },
        children: [],
      },
      {
        id: "C202839",
        name: "RING",
        totalProducts: 9,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 9,
        },
        children: [],
      },
      {
        id: "C202829",
        name: "SCARF",
        totalProducts: 22,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 22,
        },
        children: [],
      },
    ],
  },
  {
    id: "C7744",
    name: "LEATHER GOODS",
    totalProducts: 225,
    kpis: {
      targetValue: 0,
      inprocessValue: 0,
      confirmValue: 0,
      validatedValue: 0,
      totalValue: 0,
      totalVsTargetValue: 0,
      totalVsTargetValuePerc: 0,
      mixTargetValue: 0,
      mixActualValue: 0,
      targetQuantity: 0,
      inprocessQuantity: 0,
      confirmQuantity: 0,
      validatedQuantity: 0,
      totalVsTargetQuantity: 0,
      totalVsTargetQuantityPerc: 0,
      mixTargetQuantity: 0,
      mixActualQuantity: 0,
      nbAcsBuy: 0,
      acs: 225,
    },
    children: [
      {
        id: "C202819",
        name: "BELTS",
        totalProducts: 13,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 13,
        },
        children: [
          {
            id: "C229069",
            name: "OTHER",
            totalProducts: 13,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 13,
            },
            children: [],
          },
        ],
      },
      {
        id: "C202812",
        name: "LLG",
        totalProducts: 135,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 135,
        },
        children: [
          {
            id: "C229625",
            name: "4G",
            totalProducts: 46,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 46,
            },
            children: [],
          },
          {
            id: "C229912",
            name: "4G LIGHT",
            totalProducts: 6,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 6,
            },
            children: [],
          },
          {
            id: "C229247",
            name: "ANTIGONA",
            totalProducts: 49,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 49,
            },
            children: [],
          },
          {
            id: "C229784",
            name: "ANTIGONA SOFT",
            totalProducts: 13,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 13,
            },
            children: [],
          },
          {
            id: "C229870",
            name: "CUT OUT",
            totalProducts: 10,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 10,
            },
            children: [],
          },
          {
            id: "C229351",
            name: "PANDORA",
            totalProducts: 9,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 9,
            },
            children: [],
          },
          {
            id: "C229690",
            name: "WING",
            totalProducts: 2,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 2,
            },
            children: [],
          },
        ],
      },
      {
        id: "C202881",
        name: "MLG",
        totalProducts: 11,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 11,
        },
        children: [
          {
            id: "C229247",
            name: "ANTIGONA",
            totalProducts: 11,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 11,
            },
            children: [],
          },
        ],
      },
      {
        id: "C202813",
        name: "SLG",
        totalProducts: 66,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 66,
        },
        children: [
          {
            id: "C229625",
            name: "4G",
            totalProducts: 43,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 43,
            },
            children: [],
          },
          {
            id: "C229247",
            name: "ANTIGONA",
            totalProducts: 8,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 8,
            },
            children: [],
          },
          {
            id: "C229870",
            name: "CUT OUT",
            totalProducts: 4,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 4,
            },
            children: [],
          },
          {
            id: "C229083",
            name: "EDGE",
            totalProducts: 7,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 7,
            },
            children: [],
          },
          {
            id: "C229069",
            name: "OTHER",
            totalProducts: 4,
            kpis: {
              targetValue: 0,
              inprocessValue: 0,
              confirmValue: 0,
              validatedValue: 0,
              totalValue: 0,
              totalVsTargetValue: 0,
              totalVsTargetValuePerc: 0,
              mixTargetValue: 0,
              mixActualValue: 0,
              targetQuantity: 0,
              inprocessQuantity: 0,
              confirmQuantity: 0,
              validatedQuantity: 0,
              totalVsTargetQuantity: 0,
              totalVsTargetQuantityPerc: 0,
              mixTargetQuantity: 0,
              mixActualQuantity: 0,
              nbAcsBuy: 0,
              acs: 4,
            },
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "C7742",
    name: "READY TO WEAR",
    totalProducts: 211,
    kpis: {
      targetValue: 102,
      inprocessValue: 0,
      confirmValue: 0,
      validatedValue: 0,
      totalValue: 0,
      totalVsTargetValue: -102,
      totalVsTargetValuePerc: 0,
      mixTargetValue: 100,
      mixActualValue: 0,
      targetQuantity: 956,
      inprocessQuantity: 0,
      confirmQuantity: 0,
      validatedQuantity: 0,
      totalVsTargetQuantity: -956,
      totalVsTargetQuantityPerc: 0,
      mixTargetQuantity: 100,
      mixActualQuantity: 0,
      nbAcsBuy: 0,
      acs: 211,
    },
    children: [
      {
        id: "C202802",
        name: "COAT",
        totalProducts: 5,
        kpis: {
          targetValue: 10,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: -10,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 9.8,
          mixActualValue: 0,
          targetQuantity: 85,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: -85,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 8.89,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 5,
        },
        children: [],
      },
      {
        id: "C202808",
        name: "DRESS",
        totalProducts: 36,
        kpis: {
          targetValue: 21,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: -21,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 20.59,
          mixActualValue: 0,
          targetQuantity: 214,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: -214,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 22.38,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 36,
        },
        children: [],
      },
      {
        id: "C202803",
        name: "JACKET",
        totalProducts: 9,
        kpis: {
          targetValue: 14,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: -14,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 13.73,
          mixActualValue: 0,
          targetQuantity: 119,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: -119,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 12.45,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 9,
        },
        children: [],
      },
      {
        id: "C202801",
        name: "OUTERWEAR",
        totalProducts: 24,
        kpis: {
          targetValue: 21,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: -21,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 20.59,
          mixActualValue: 0,
          targetQuantity: 214,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: -214,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 22.38,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 24,
        },
        children: [],
      },
      {
        id: "C202804",
        name: "SHIRT / TOP",
        totalProducts: 22,
        kpis: {
          targetValue: 15,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: -15,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 14.71,
          mixActualValue: 0,
          targetQuantity: 110,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: -110,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 11.51,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 22,
        },
        children: [],
      },
      {
        id: "C202807",
        name: "SKIRT",
        totalProducts: 15,
        kpis: {
          targetValue: 21,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: -21,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 20.59,
          mixActualValue: 0,
          targetQuantity: 214,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: -214,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 22.38,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 15,
        },
        children: [],
      },
      {
        id: "C202810",
        name: "SWEATER",
        totalProducts: 21,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 21,
        },
        children: [],
      },
      {
        id: "C202880",
        name: "SWEATSHIRT",
        totalProducts: 13,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 13,
        },
        children: [],
      },
      {
        id: "C202805",
        name: "T-SHIRT/POLO",
        totalProducts: 23,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 23,
        },
        children: [],
      },
      {
        id: "C202806",
        name: "TROUSERS",
        totalProducts: 39,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 39,
        },
        children: [],
      },
      {
        id: "C202814",
        name: "UNDERWEAR",
        totalProducts: 4,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 4,
        },
        children: [],
      },
    ],
  },
  {
    id: "C7746",
    name: "SHOES",
    totalProducts: 115,
    kpis: {
      targetValue: 0,
      inprocessValue: 6500,
      confirmValue: 0,
      validatedValue: 0,
      totalValue: 6500,
      totalVsTargetValue: 6500,
      totalVsTargetValuePerc: 0,
      mixTargetValue: 0,
      mixActualValue: 90.53,
      targetQuantity: 0,
      inprocessQuantity: 27412,
      confirmQuantity: 28,
      validatedQuantity: 898,
      totalQuantity: 28338,
      totalVsTargetQuantity: 28338,
      totalVsTargetQuantityPerc: 0,
      mixTargetQuantity: 0,
      mixActualQuantity: 99.99,
      nbAcsBuy: 11,
      acs: 115,
    },
    children: [
      {
        id: "C229591",
        name: "4G",
        totalProducts: 6,
        kpis: {
          targetValue: 0,
          inprocessValue: 6500,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 6500,
          totalVsTargetValue: 6500,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 100,
          targetQuantity: 0,
          inprocessQuantity: 27407,
          confirmQuantity: 16,
          validatedQuantity: 798,
          totalQuantity: 28221,
          totalVsTargetQuantity: 28221,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 99.59,
          nbAcsBuy: 6,
          acs: 6,
        },
        children: [],
      },
      {
        id: "C229508",
        name: "BEDFORD",
        totalProducts: 6,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 5,
          confirmQuantity: 12,
          validatedQuantity: 0,
          totalQuantity: 17,
          totalVsTargetQuantity: 17,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0.06,
          nbAcsBuy: 3,
          acs: 6,
        },
        children: [],
      },
      {
        id: "C229763",
        name: "CITY",
        totalProducts: 6,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 6,
        },
        children: [],
      },
      {
        id: "C229893",
        name: "G",
        totalProducts: 5,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 50,
          totalQuantity: 50,
          totalVsTargetQuantity: 50,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0.18,
          nbAcsBuy: 1,
          acs: 5,
        },
        children: [],
      },
      {
        id: "C229904",
        name: "G CHAIN",
        totalProducts: 20,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 20,
        },
        children: [],
      },
      {
        id: "C229895",
        name: "GIV 1",
        totalProducts: 10,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 10,
        },
        children: [],
      },
      {
        id: "C229891",
        name: "GIV RUNNER",
        totalProducts: 4,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 50,
          totalQuantity: 50,
          totalVsTargetQuantity: 50,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0.18,
          nbAcsBuy: 1,
          acs: 4,
        },
        children: [],
      },
      {
        id: "C229892",
        name: "HORN",
        totalProducts: 2,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 2,
        },
        children: [],
      },
      {
        id: "C229894",
        name: "LOCK",
        totalProducts: 6,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 6,
        },
        children: [],
      },
      {
        id: "C229179",
        name: "LOOK BOOK",
        totalProducts: 9,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 9,
        },
        children: [],
      },
      {
        id: "C229896",
        name: "MARSHMALLOW",
        totalProducts: 14,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 14,
        },
        children: [],
      },
      {
        id: "C229176",
        name: "SLIDE",
        totalProducts: 6,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 6,
        },
        children: [],
      },
      {
        id: "C229742",
        name: "SPECTRE",
        totalProducts: 5,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 5,
        },
        children: [],
      },
      {
        id: "C229890",
        name: "SQUARED",
        totalProducts: 8,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 8,
        },
        children: [],
      },
      {
        id: "C229281",
        name: "URBAN STREET123",
        totalProducts: 8,
        kpis: {
          targetValue: 0,
          inprocessValue: 0,
          confirmValue: 0,
          validatedValue: 0,
          totalValue: 0,
          totalVsTargetValue: 0,
          totalVsTargetValuePerc: 0,
          mixTargetValue: 0,
          mixActualValue: 0,
          targetQuantity: 0,
          inprocessQuantity: 0,
          confirmQuantity: 0,
          validatedQuantity: 0,
          totalQuantity: 0,
          totalVsTargetQuantity: 0,
          totalVsTargetQuantityPerc: 0,
          mixTargetQuantity: 0,
          mixActualQuantity: 0,
          nbAcsBuy: 0,
          acs: 8,
        },
        children: [],
      },
    ],
  },
];

function App() {
  const rerender = useReducer(() => ({}), {})[1];
  const [columnPinning, setColumnPinning] = useState<ColumnPinningState>({
    left: ["name"],
    right: [],
  });
  const [selectedCell, setSelectedCell] = useState<{
    rowId: string;
    columnId: string;
  } | null>(null);
  const [columnResizeMode, setColumnResizeMode] =
    useState<ColumnResizeMode>("onChange");
  type ColumnPinningState = {
    left?: string[];
    right?: string[];
  };

  const columns = [
    columnHelper.accessor("name", {
      header: ({ column }) => (
        <div>
          Name <button onClick={() => togglePin(column.id)}>📌</button>
        </div>
      ),
      cell: ({ row, getValue }) => (
        <>
          {row.getCanExpand() ? (
            <button
              onClick={row.getToggleExpandedHandler()}
              style={{ marginRight: "0.5rem" }}
            >
              {row.getIsExpanded() ? "▼" : "▶"}
            </button>
          ) : null}
          {getValue()}
        </>
      ),
    }),
    ...[
      "totalProducts",
      "targetValue",
      "inprocessValue",
      "confirmValue",
      "validatedValue",
      "totalValue",
      "totalVsTargetValue",
      "totalVsTargetValuePerc",
      "mixTargetValue",
      "mixActualValue",
      "targetQuantity",
      "inprocessQuantity",
      "confirmQuantity",
      "validatedQuantity",
      "totalQuantity",
      "totalVsTargetQuantity",
      "totalVsTargetQuantityPerc",
      "mixTargetQuantity",
      "mixActualQuantity",
      "nbAcsBuy",
      "acs",
    ].map((key) =>
      columnHelper.accessor(
        (row: Category) =>
          key === "totalProducts"
            ? row.totalProducts
            : row.kpis[key as keyof KPIs],
        {
          id: key,
          header: ({ column }) => (
            <div>
              {key.charAt(0).toUpperCase() + key.slice(1)}{" "}
              <button onClick={() => togglePin(column.id)}>📌</button>
            </div>
          ),
          cell: (info) => info.renderValue(),
        }
      )
    ),
  ];

  const table = useReactTable<Category>({
    data: testData,
    columns,
    defaultColumn: {
      size: 200, // or whatever you want as the default
      minSize: 50,
      maxSize: 600,
    },

    state: {
      columnPinning,
    },
    // columnResizeMode,
    //ColumnResizeDirection,
    onColumnPinningChange: setColumnPinning,
    getCoreRowModel: getCoreRowModel(),
    getExpandedRowModel: getExpandedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    enableExpanding: true,
    enablePinning: true,
    enableColumnResizing: true,
    columnResizeMode: columnResizeMode,
    getSubRows: (row) => row.children ?? [],
  });

  function togglePin(columnId: string) {
    setColumnPinning((old) => {
      const isPinned = old.left?.includes(columnId);
      return {
        ...old,
        left: isPinned
          ? old.left?.filter((id) => id !== columnId)
          : [...(old.left ?? []), columnId],
      };
    });
  }

  return (
    <div className="p-4">
      <table>
        <thead>
          {table.getHeaderGroups().map((headerGroup) => (
            <tr key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <th
                  key={header.id}
                  style={{
                    width: `${header.getSize()}px`,
                    minWidth: `${header.column.columnDef.minSize ?? 50}px`,
                    maxWidth: `${header.column.columnDef.maxSize ?? 400}px`,
                    position: header.column.getIsPinned()
                      ? "sticky"
                      : "relative",
                    left:
                      header.column.getIsPinned() === "left"
                        ? `${header.column.getStart("left")}px`
                        : undefined,
                    zIndex: header.column.getIsPinned() ? 1 : 0,
                    background: header.column.getIsPinned()
                      ? "#f0f0f0"
                      : undefined,
                  }}
                >
                  {header.isPlaceholder
                    ? null
                    : flexRender(
                        header.column.columnDef.header,
                        header.getContext()
                      )}
                  {!header.isPlaceholder && header.column.getCanResize?.() && (
                    <div
                      onMouseDown={header.getResizeHandler()}
                      onTouchStart={header.getResizeHandler()}
                      style={{
                        position: "absolute",
                        right: 0,
                        top: 0,
                        height: "100%",
                        width: "5px",
                        cursor: "col-resize",
                        userSelect: "none",
                        touchAction: "none",
                        zIndex: 10,
                      }}
                    />
                  )}
                </th>
              ))}
            </tr>
          ))}
        </thead>
        <tbody>
          {table.getRowModel().rows.map((row) => (
            <tr key={row.id}>
              {row.getVisibleCells().map((cell) => (
                <td
                  key={cell.id}
                  onClick={() =>
                    setSelectedCell({ rowId: row.id, columnId: cell.column.id })
                  }
                  className={
                    selectedCell &&
                    selectedCell.rowId === row.id &&
                    selectedCell.columnId === cell.column.id
                      ? "selected-cell"
                      : ""
                  }
                  style={{
                    width: `${cell.column.getSize()}px`,
                    minWidth: `${cell.column.columnDef.minSize ?? 50}px`,
                    maxWidth: `${cell.column.columnDef.maxSize ?? 400}px`,
                    position: cell.column.getIsPinned() ? "sticky" : "relative",
                    left:
                      cell.column.getIsPinned() === "left"
                        ? `${cell.column.getStart("left")}px`
                        : undefined,
                    background: cell.column.getIsPinned() ? "#fff" : undefined,
                    zIndex: cell.column.getIsPinned() ? 1 : 0,
                    paddingLeft: `${row.depth * 1.5}rem`,
                  }}
                >
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
      <div style={{ marginTop: 12 }}>
        <button onClick={() => rerender()} style={{ padding: "6px 12px" }}>
          Rerender
        </button>
      </div>
    </div>
  );
}

export default App;
